# Generated by Django 4.0.6 on 2022-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="maillist_id",
            new_name="mail_list_id",
        ),
        migrations.AlterField(
            model_name="message",
            name="status_of_send",
            field=models.CharField(
                choices=[("NONE", "none"), ("SUCCESS", "success"), ("FAIL", "fail")],
                default="NONE",
                max_length=8,
                verbose_name="Статус отправки",
            ),
        ),
    ]
